/*
 * Java bean class for entity table course_instructors 
 * Created on 14 Jul 2015 ( Date ISO 2015-07-14 - Time 20:55:45 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package models;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * Entity bean for table "course_instructors"
 * 
 * @author Telosys Tools Generator
 *
 */
@Entity
@Table
public class CourseInstructors implements Serializable
{
    private static final long serialVersionUID = 1L;

    @Id
    private Integer    instructorid ; // Primary Key
    private Integer    courseid     ; // Primary Key


    /**
     * Default constructor
     */
    public CourseInstructors()
    {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR THE PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "instructorid" field value
     * This field is mapped on the database column "InstructorId" ( type "INT", NotNull : true ) 
     * @param instructorid
     */
	public void setInstructorid( Integer instructorid )
    {
        this.instructorid = instructorid ;
    }
    /**
     * Get the "instructorid" field value
     * This field is mapped on the database column "InstructorId" ( type "INT", NotNull : true ) 
     * @return the field value
     */
	public Integer getInstructorid()
    {
        return this.instructorid;
    }
    /**
     * Set the "courseid" field value
     * This field is mapped on the database column "CourseId" ( type "INT", NotNull : true ) 
     * @param courseid
     */
	public void setCourseid( Integer courseid )
    {
        this.courseid = courseid ;
    }
    /**
     * Get the "courseid" field value
     * This field is mapped on the database column "CourseId" ( type "INT", NotNull : true ) 
     * @return the field value
     */
	public Integer getCourseid()
    {
        return this.courseid;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR DATA FIELDS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(instructorid);
        sb.append("|");
        sb.append(courseid);
        return sb.toString(); 
    } 


}
