/*
 * Java bean class for entity table courses 
 * Created on 14 Jul 2015 ( Date ISO 2015-07-14 - Time 20:55:45 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package models;

import java.io.Serializable;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;


/**
 * Entity bean for table "courses"
 * 
 * @author Telosys Tools Generator
 *
 */
@Entity
@Table(name="courses")
public class Course implements Serializable
{
    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) 
    private Integer    id           ; // Primary Key

    private String     name         ;
    private Byte       required     ;
    private Byte       nolectures   ;
    private Byte       noaudit      ;
    private Byte       nolab        ;
    //private Integer    semesterid   ;
    //private Integer    departmentid ;
    
    @ManyToOne
    @JoinColumn(name="SemesterId")
    private Semester semester;
    
    @ManyToOne
    @JoinColumn(name="DepartmentId")
    private Department department;
    
    @ManyToMany
    @JoinTable(name="course_instructors",
    		joinColumns= @JoinColumn(name="CourseId"),
    		inverseJoinColumns = @JoinColumn(name="InstructorId")
    )
    private List<FacultyPersonnel> instructors;
    
    @OneToMany(mappedBy="course")
    private List<Group> groups;
    
    /**
     * Default constructor
     */
    public Course()
    {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR THE PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "id" field value
     * This field is mapped on the database column "Id" ( type "INT", NotNull : true ) 
     * @param id
     */
	public void setId( Integer id )
    {
        this.id = id ;
    }
    /**
     * Get the "id" field value
     * This field is mapped on the database column "Id" ( type "INT", NotNull : true ) 
     * @return the field value
     */
	public Integer getId()
    {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR DATA FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : Name ( VARCHAR ) 
    /**
     * Set the "name" field value
     * This field is mapped on the database column "Name" ( type "VARCHAR", NotNull : true ) 
     * @param name
     */
    public void setName( String name )
    {
        this.name = name;
    }
    /**
     * Get the "name" field value
     * This field is mapped on the database column "Name" ( type "VARCHAR", NotNull : true ) 
     * @return the field value
     */
    public String getName()
    {
        return this.name;
    }

    //--- DATABASE MAPPING : Required ( TINYINT ) 
    /**
     * Set the "required" field value
     * This field is mapped on the database column "Required" ( type "TINYINT", NotNull : true ) 
     * @param required
     */
    public void setRequired( Byte required )
    {
        this.required = required;
    }
    /**
     * Get the "required" field value
     * This field is mapped on the database column "Required" ( type "TINYINT", NotNull : true ) 
     * @return the field value
     */
    public Byte getRequired()
    {
        return this.required;
    }

    //--- DATABASE MAPPING : NoLectures ( TINYINT ) 
    /**
     * Set the "nolectures" field value
     * This field is mapped on the database column "NoLectures" ( type "TINYINT", NotNull : false ) 
     * @param nolectures
     */
    public void setNolectures( Byte nolectures )
    {
        this.nolectures = nolectures;
    }
    /**
     * Get the "nolectures" field value
     * This field is mapped on the database column "NoLectures" ( type "TINYINT", NotNull : false ) 
     * @return the field value
     */
    public Byte getNolectures()
    {
        return this.nolectures;
    }

    //--- DATABASE MAPPING : NoAudit ( TINYINT ) 
    /**
     * Set the "noaudit" field value
     * This field is mapped on the database column "NoAudit" ( type "TINYINT", NotNull : false ) 
     * @param noaudit
     */
    public void setNoaudit( Byte noaudit )
    {
        this.noaudit = noaudit;
    }
    /**
     * Get the "noaudit" field value
     * This field is mapped on the database column "NoAudit" ( type "TINYINT", NotNull : false ) 
     * @return the field value
     */
    public Byte getNoaudit()
    {
        return this.noaudit;
    }

    //--- DATABASE MAPPING : NoLab ( TINYINT ) 
    /**
     * Set the "nolab" field value
     * This field is mapped on the database column "NoLab" ( type "TINYINT", NotNull : false ) 
     * @param nolab
     */
    public void setNolab( Byte nolab )
    {
        this.nolab = nolab;
    }
    /**
     * Get the "nolab" field value
     * This field is mapped on the database column "NoLab" ( type "TINYINT", NotNull : false ) 
     * @return the field value
     */
    public Byte getNolab()
    {
        return this.nolab;
    }

    //--- DATABASE MAPPING : SemesterId ( INT ) 
    /**
     * Set the "semesterid" field value
     * This field is mapped on the database column "SemesterId" ( type "INT", NotNull : true ) 
     * @param semesterid
     
    public void setSemesterid( Integer semesterid )
    {
        this.semesterid = semesterid;
    }
    /**
     * Get the "semesterid" field value
     * This field is mapped on the database column "SemesterId" ( type "INT", NotNull : true ) 
     * @return the field value
     
    public Integer getSemesterid()
    {
        return this.semesterid;
    }

    //--- DATABASE MAPPING : DepartmentId ( INT ) 
    /**
     * Set the "departmentid" field value
     * This field is mapped on the database column "DepartmentId" ( type "INT", NotNull : true ) 
     * @param departmentid
     
    public void setDepartmentid( Integer departmentid )
    {
        this.departmentid = departmentid;
    }
    /**
     * Get the "departmentid" field value
     * This field is mapped on the database column "DepartmentId" ( type "INT", NotNull : true ) 
     * @return the field value
     
    public Integer getDepartmentid()
    {
        return this.departmentid;
    }
    */

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(required);
        sb.append("|");
        sb.append(nolectures);
        sb.append("|");
        sb.append(noaudit);
        sb.append("|");
        sb.append(nolab);
        sb.append("|");
        sb.append(semester.getName());
        sb.append("|");
        sb.append(department.getName());
        return sb.toString(); 
    }

	public Semester getSemester() {
		return semester;
	}

	public void setSemester(Semester semester) {
		this.semester = semester;
	}

	public List<FacultyPersonnel> getInstructors() {
		return instructors;
	}

	public void setInstructors(List<FacultyPersonnel> instructors) {
		this.instructors = instructors;
	}

	public Department getDepartment() {
		return department;
	}

	public void setDepartment(Department departmnet) {
		this.department = departmnet;
	}

	public List<Group> getGroups() {
		return groups;
	}

	public void setGroups(List<Group> groups) {
		this.groups = groups;
	} 


}
