/*
 * Java bean class for entity table departments 
 * Created on 14 Jul 2015 ( Date ISO 2015-07-14 - Time 20:55:45 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package models;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * Entity bean for table "departments"
 * 
 * @author Telosys Tools Generator
 *
 */
@Entity
@Table(name="departments")
public class Department implements Serializable
{
    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO) 
    private Integer    id           ; // Primary Key

    private String     name         ;
    private String     departmentchiefid ;

    /**
     * Default constructor
     */
    public Department()
    {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR THE PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "id" field value
     * This field is mapped on the database column "Id" ( type "INT", NotNull : true ) 
     * @param id
     */
	public void setId( Integer id )
    {
        this.id = id ;
    }
    /**
     * Get the "id" field value
     * This field is mapped on the database column "Id" ( type "INT", NotNull : true ) 
     * @return the field value
     */
	public Integer getId()
    {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR DATA FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : Name ( VARCHAR ) 
    /**
     * Set the "name" field value
     * This field is mapped on the database column "Name" ( type "VARCHAR", NotNull : true ) 
     * @param name
     */
    public void setName( String name )
    {
        this.name = name;
    }
    /**
     * Get the "name" field value
     * This field is mapped on the database column "Name" ( type "VARCHAR", NotNull : true ) 
     * @return the field value
     */
    public String getName()
    {
        return this.name;
    }

    //--- DATABASE MAPPING : DepartmentChiefId ( VARCHAR ) 
    /**
     * Set the "departmentchiefid" field value
     * This field is mapped on the database column "DepartmentChiefId" ( type "VARCHAR", NotNull : false ) 
     * @param departmentchiefid
     */
    public void setDepartmentchiefid( String departmentchiefid )
    {
        this.departmentchiefid = departmentchiefid;
    }
    /**
     * Get the "departmentchiefid" field value
     * This field is mapped on the database column "DepartmentChiefId" ( type "VARCHAR", NotNull : false ) 
     * @return the field value
     */
    public String getDepartmentchiefid()
    {
        return this.departmentchiefid;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(departmentchiefid);
        return sb.toString(); 
    } 


}
