/*
 * Java bean class for entity table groups 
 * Created on 14 Jul 2015 ( Date ISO 2015-07-14 - Time 20:55:46 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package models;

import java.io.Serializable;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;


/**
 * Entity bean for table "groups"
 * 
 * @author Telosys Tools Generator
 *
 */
@Entity
@Table(name="groups")
public class Group implements Serializable
{
    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) 
    private Integer    id           ; // Primary Key

    private String     type         ;
    private String     name         ;
    //private Integer    courseid     ;
    //private Integer    instructorid ;

    @ManyToOne
    @JoinColumn(name="InstructorId")
    private FacultyPersonnel instructor;
    
    @ManyToOne
    @JoinColumn(name="CourseId")
    private Course course;
    
    @ManyToMany
    @JoinTable(name="students_groups",
    		joinColumns= @JoinColumn(name="GroupId"),
    		inverseJoinColumns = @JoinColumn(name="StudentId")
    )
    private List<Student> students;
    
    @OneToOne(mappedBy="group")
    private TimeSlot timeSlot;
    
    /**
     * Default constructor
     */
    public Group()
    {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR THE PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "id" field value
     * This field is mapped on the database column "Id" ( type "INT", NotNull : true ) 
     * @param id
     */
	public void setId( Integer id )
    {
        this.id = id ;
    }
    /**
     * Get the "id" field value
     * This field is mapped on the database column "Id" ( type "INT", NotNull : true ) 
     * @return the field value
     */
	public Integer getId()
    {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR DATA FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : Type ( VARCHAR ) 
    /**
     * Set the "type" field value
     * This field is mapped on the database column "Type" ( type "VARCHAR", NotNull : true ) 
     * @param type
     */
    public void setType( String type )
    {
        this.type = type;
    }
    /**
     * Get the "type" field value
     * This field is mapped on the database column "Type" ( type "VARCHAR", NotNull : true ) 
     * @return the field value
     */
    public String getType()
    {
        return this.type;
    }

    //--- DATABASE MAPPING : Name ( VARCHAR ) 
    /**
     * Set the "name" field value
     * This field is mapped on the database column "Name" ( type "VARCHAR", NotNull : true ) 
     * @param name
     */
    public void setName( String name )
    {
        this.name = name;
    }
    /**
     * Get the "name" field value
     * This field is mapped on the database column "Name" ( type "VARCHAR", NotNull : true ) 
     * @return the field value
     */
    public String getName()
    {
        return this.name;
    }

    //--- DATABASE MAPPING : CourseId ( INT ) 
    /**
     * Set the "courseid" field value
     * This field is mapped on the database column "CourseId" ( type "INT", NotNull : true ) 
     * @param courseid
     
    public void setCourseid( Integer courseid )
    {
        this.courseid = courseid;
    }
    /**
     * Get the "courseid" field value
     * This field is mapped on the database column "CourseId" ( type "INT", NotNull : true ) 
     * @return the field value
     
    public Integer getCourseid()
    {
        return this.courseid;
    }

    //--- DATABASE MAPPING : InstructorId ( INT ) 
    /**
     * Set the "instructorid" field value
     * This field is mapped on the database column "InstructorId" ( type "INT", NotNull : true ) 
     * @param instructorid
     
    public void setInstructorid( Integer instructorid )
    {
        this.instructorid = instructorid;
    }
    /**
     * Get the "instructorid" field value
     * This field is mapped on the database column "InstructorId" ( type "INT", NotNull : true ) 
     * @return the field value
     
    public Integer getInstructorid()
    {
        return this.instructorid;
    }
    */
    public List<Student> getStudents()
    {
        return this.students;
    }
    
    public void setStudents(List<Student> s)
    {
        this.students = s;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(type);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(course.getName());
        sb.append("|");
        sb.append(getInstructor());
        return sb.toString(); 
    }

	public Course getCourse() {
		return course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public TimeSlot getTimeSlot() {
		return timeSlot;
	}

	public void setTimeSlot(TimeSlot timeSlot) {
		this.timeSlot = timeSlot;
	}

	public FacultyPersonnel getInstructor() {
		return instructor;
	}

	public void setInstructor(FacultyPersonnel instructor) {
		this.instructor = instructor;
	} 


}
