/*
 * Java bean class for entity table reservations 
 * Created on 14 Jul 2015 ( Date ISO 2015-07-14 - Time 20:55:46 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package models;

import java.io.Serializable;

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Entity bean for table "reservations"
 * 
 * @author Telosys Tools Generator
 *
 */
@Entity
@Table(name="reservations")
public class Reservation implements Serializable
{
    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) 
    private Integer    id           ; // Primary Key

    private String     type         ;
    private Float starttime;
    private Float endtime;
    @Temporal(TemporalType.DATE)
    private Date       begindatetime ;
    
    //private Integer    reservedbyid ;
    //private Integer    roomid       ;

    @ManyToOne
    @JoinColumn(name="ReservedbyId")
    private FacultyPersonnel reservedBy;
    
    @ManyToOne
    @JoinColumn(name="RoomId")
    private Room room;
    
    /**
     * Default constructor
     */
    public Reservation()
    {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR THE PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "id" field value
     * This field is mapped on the database column "Id" ( type "INT", NotNull : true ) 
     * @param id
     */
	public void setId( Integer id )
    {
        this.id = id ;
    }
    /**
     * Get the "id" field value
     * This field is mapped on the database column "Id" ( type "INT", NotNull : true ) 
     * @return the field value
     */
	public Integer getId()
    {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR DATA FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : Type ( VARCHAR ) 
    /**
     * Set the "type" field value
     * This field is mapped on the database column "Type" ( type "VARCHAR", NotNull : true ) 
     * @param type
     */
    public void setType( String type )
    {
        this.type = type;
    }
    /**
     * Get the "type" field value
     * This field is mapped on the database column "Type" ( type "VARCHAR", NotNull : true ) 
     * @return the field value
     */
    public String getType()
    {
        return this.type;
    }

    //--- DATABASE MAPPING : BeginDateTime ( DATETIME ) 
    /**
     * Set the "begindatetime" field value
     * This field is mapped on the database column "BeginDateTime" ( type "DATETIME", NotNull : true ) 
     * @param begindatetime
     */
    public void setBegindatetime( Date begindatetime )
    {
        this.begindatetime = begindatetime;
    }
    /**
     * Get the "begindatetime" field value
     * This field is mapped on the database column "BeginDateTime" ( type "DATETIME", NotNull : true ) 
     * @return the field value
     */
    public Date getBegindatetime()
    {
        return this.begindatetime;
    }

    //--- DATABASE MAPPING : EndDateTime ( DATETIME ) 
    /**
     * Set the "enddatetime" field value
     * This field is mapped on the database column "EndDateTime" ( type "DATETIME", NotNull : true ) 
     * @param enddatetime
     */
    
    /**
     * Get the "enddatetime" field value
     * This field is mapped on the database column "EndDateTime" ( type "DATETIME", NotNull : true ) 
     * @return the field value
     */
    

    //--- DATABASE MAPPING : ReservedById ( INT ) 
    /**
     * Set the "reservedbyid" field value
     * This field is mapped on the database column "ReservedById" ( type "INT", NotNull : true ) 
     * @param reservedbyid
    
    public void setReservedbyid( Integer reservedbyid )
    {
        this.reservedbyid = reservedbyid;
    }
    /**
     * Get the "reservedbyid" field value
     * This field is mapped on the database column "ReservedById" ( type "INT", NotNull : true ) 
     * @return the field value
     
    public Integer getReservedbyid()
    {
        return this.reservedbyid;
    }

    //--- DATABASE MAPPING : RoomId ( INT ) 
    /**
     * Set the "roomid" field value
     * This field is mapped on the database column "RoomId" ( type "INT", NotNull : true ) 
     * @param roomid
     
    public void setRoomid( Integer roomid )
    {
        this.roomid = roomid;
    }
    /**
     * Get the "roomid" field value
     * This field is mapped on the database column "RoomId" ( type "INT", NotNull : true ) 
     * @return the field value
     
    public Integer getRoomid()
    {
        return this.roomid;
    }
	*/

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        
        sb.append(type);
        sb.append("|");
        sb.append(begindatetime);
        sb.append("|");
        sb.append(reservedBy);
        sb.append("|");
        sb.append(room);
        return sb.toString(); 
    }

	public FacultyPersonnel getReservedBy() {
		return reservedBy;
	}

	public void setReservedBy(FacultyPersonnel reservedBy) {
		this.reservedBy = reservedBy;
	}

	public Room getRoom() {
		return room;
	}

	public void setRoom(Room room) {
		this.room = room;
	}

	public Float getStarttime() {
		return starttime;
	}

	public void setStarttime(Float starttime) {
		this.starttime = starttime;
	}

	public Float getEndtime() {
		return endtime;
	}

	public void setEndtime(Float endtime) {
		this.endtime = endtime;
	}


}
