/*
 * Java bean class for entity table students 
 * Created on 14 Jul 2015 ( Date ISO 2015-07-14 - Time 20:55:47 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package models;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * Entity bean for table "students"
 * 
 * @author Telosys Tools Generator
 *
 */
@Entity
@Table
public class Students implements Serializable
{
    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO) 
    private Integer    id           ; // Primary Key

    private String     name         ;
    private String     lastname     ;
    private String     studentid    ;
    private Integer    departmentid ;
    private Integer    semesterid   ;

    /**
     * Default constructor
     */
    public Students()
    {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR THE PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "id" field value
     * This field is mapped on the database column "Id" ( type "INT", NotNull : true ) 
     * @param id
     */
	public void setId( Integer id )
    {
        this.id = id ;
    }
    /**
     * Get the "id" field value
     * This field is mapped on the database column "Id" ( type "INT", NotNull : true ) 
     * @return the field value
     */
	public Integer getId()
    {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR DATA FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : Name ( VARCHAR ) 
    /**
     * Set the "name" field value
     * This field is mapped on the database column "Name" ( type "VARCHAR", NotNull : true ) 
     * @param name
     */
    public void setName( String name )
    {
        this.name = name;
    }
    /**
     * Get the "name" field value
     * This field is mapped on the database column "Name" ( type "VARCHAR", NotNull : true ) 
     * @return the field value
     */
    public String getName()
    {
        return this.name;
    }

    //--- DATABASE MAPPING : Lastname ( VARCHAR ) 
    /**
     * Set the "lastname" field value
     * This field is mapped on the database column "Lastname" ( type "VARCHAR", NotNull : true ) 
     * @param lastname
     */
    public void setLastname( String lastname )
    {
        this.lastname = lastname;
    }
    /**
     * Get the "lastname" field value
     * This field is mapped on the database column "Lastname" ( type "VARCHAR", NotNull : true ) 
     * @return the field value
     */
    public String getLastname()
    {
        return this.lastname;
    }

    //--- DATABASE MAPPING : StudentId ( VARCHAR ) 
    /**
     * Set the "studentid" field value
     * This field is mapped on the database column "StudentId" ( type "VARCHAR", NotNull : true ) 
     * @param studentid
     */
    public void setStudentid( String studentid )
    {
        this.studentid = studentid;
    }
    /**
     * Get the "studentid" field value
     * This field is mapped on the database column "StudentId" ( type "VARCHAR", NotNull : true ) 
     * @return the field value
     */
    public String getStudentid()
    {
        return this.studentid;
    }

    //--- DATABASE MAPPING : DepartmentId ( INT ) 
    /**
     * Set the "departmentid" field value
     * This field is mapped on the database column "DepartmentId" ( type "INT", NotNull : true ) 
     * @param departmentid
     */
    public void setDepartmentid( Integer departmentid )
    {
        this.departmentid = departmentid;
    }
    /**
     * Get the "departmentid" field value
     * This field is mapped on the database column "DepartmentId" ( type "INT", NotNull : true ) 
     * @return the field value
     */
    public Integer getDepartmentid()
    {
        return this.departmentid;
    }

    //--- DATABASE MAPPING : SemesterId ( INT ) 
    /**
     * Set the "semesterid" field value
     * This field is mapped on the database column "SemesterId" ( type "INT", NotNull : true ) 
     * @param semesterid
     */
    public void setSemesterid( Integer semesterid )
    {
        this.semesterid = semesterid;
    }
    /**
     * Get the "semesterid" field value
     * This field is mapped on the database column "SemesterId" ( type "INT", NotNull : true ) 
     * @return the field value
     */
    public Integer getSemesterid()
    {
        return this.semesterid;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(lastname);
        sb.append("|");
        sb.append(studentid);
        sb.append("|");
        sb.append(departmentid);
        sb.append("|");
        sb.append(semesterid);
        return sb.toString(); 
    } 


}
