/*
 * Java bean class for entity table students_groups 
 * Created on 14 Jul 2015 ( Date ISO 2015-07-14 - Time 20:55:48 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package models;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * Entity bean for table "students_groups"
 * 
 * @author Telosys Tools Generator
 *
 */
@Entity
@Table
public class StudentsGroups implements Serializable
{
    private static final long serialVersionUID = 1L;

    @Id
    private Integer    studentid    ; // Primary Key
    private Integer    groupid      ; // Primary Key


    /**
     * Default constructor
     */
    public StudentsGroups()
    {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR THE PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "studentid" field value
     * This field is mapped on the database column "StudentId" ( type "INT", NotNull : true ) 
     * @param studentid
     */
	public void setStudentid( Integer studentid )
    {
        this.studentid = studentid ;
    }
    /**
     * Get the "studentid" field value
     * This field is mapped on the database column "StudentId" ( type "INT", NotNull : true ) 
     * @return the field value
     */
	public Integer getStudentid()
    {
        return this.studentid;
    }
    /**
     * Set the "groupid" field value
     * This field is mapped on the database column "GroupId" ( type "INT", NotNull : true ) 
     * @param groupid
     */
	public void setGroupid( Integer groupid )
    {
        this.groupid = groupid ;
    }
    /**
     * Get the "groupid" field value
     * This field is mapped on the database column "GroupId" ( type "INT", NotNull : true ) 
     * @return the field value
     */
	public Integer getGroupid()
    {
        return this.groupid;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR DATA FIELDS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(studentid);
        sb.append("|");
        sb.append(groupid);
        return sb.toString(); 
    } 


}
